baseurl = "http://127.0.0.1:1313/"
languageCode = "en-us"
title = "Nebula Graph  - An Open Source, Distributed and High Performant Graph Database"
description = "Featuring horizontal scalability, strong data consistency, high availability, and SQL-like query language, Nebula Graph database enables you to get insight out of your connected data. Get it now. For free"
theme = "creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "NebulaGraph"

		[[params.navigation.links]]
			title = "Solution"
			[[params.navigation.links.links]]
				title = "Why Nebula Graph"
				link = "/#advantage"
			[[params.navigation.links.links]]
				title = "Get Started"
				link = "https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/1.get-started.md"
				target = "_blank"
			# [[params.navigation.links.links]]
			# 	title = "Use cases"
		# [[params.navigation.links]]
		# 	title = "Customers"
		[[params.navigation.links]]
			title = "Content"
			[[params.navigation.links.links]]
				title = "Blog"
				link = "/posts"
			[[params.navigation.links.links]]
				title = "Docs"
				link = "https://github.com/vesoft-inc/nebula#documentation"
		[[params.navigation.links]]
			title = "Forum"
			link = "https://discuss.dgraph.io/"
			target = "_blank"
			# services  = "Services"
			# portfolio = "Portfolio"
			# contact   = "Contact"


	# Hero section
	[params.header]
		# To change the background of the header section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Nebula Graph"
		subtitle   = "A truly distributed, linear scalable, lighting-fast graph database."
		buttonText = "Get Started"

	# Footer section
	[params.footer]
		[[params.footer.social]]
			title = "Follow us on"
			[[params.footer.social.links]]
					title = "Twitter Profile"
					class = "icon fa fa-twitter"
					link = "https://twitter.com/NebulaGraph"
					target = "_blank"
			[[params.footer.social.links]]
					title = "WeiBo Profile"
					class = "icon fa fa-weibo"
					link = "https://weibo.com/nebulagraph"
					target = "_blank"
			[[params.footer.social.links]]
					title = "LinkedIn Profile"
					class = "icon fa fa-linkedin"
					link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
					target = "_blank"
			[[params.footer.social.links]]
					title = "YouTube Profile"
					class = "icon fa fa-youtube"
					link = "https://www.youtube.com/channel/UC73V8q795eSEMxDX4Pvdwmw"
					target = "_blank"
			[[params.footer.social.links]]
					title = "FaceBook Profile"
					class = "icon fa fa-facebook"
					link = "https://www.facebook.com/NebulaGraph/"
					target = "_blank"
			[[params.footer.social.links]]
					title = "WeChat Profile"
					class = "icon fa fa-wechat"
					modal = "btn-lg"
					id = "#myModal"
					target = "_blank"
		[[params.footer.community]]
			title = "Community"
			[[params.footer.community.links]]
					title = "GitHub"
					link = "https://github.com/vesoft-inc/nebula"
					target = "_blank"
			[[params.footer.community.links]]
					title = "Forum"
					link = "https://weibo.com/nebulagraph"
					target = "_blank"
			[[params.footer.community.links]]
					title = "Slack"
					link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
					target = "_blank"
		[[params.footer.company]]
			title = "Company"
			[[params.footer.company.links]]
					title = "About"
					link = "https://github.com/vesoft-inc/nebula"
					target = "_blank"
			[[params.footer.company.links]]
					title = "News"
					link = "https://weibo.com/nebulagraph"
					target = "_blank"
			[[params.footer.company.links]]
					title = "Contact"
					link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
					target = "_blank"
			[[params.footer.company.links]]
					title = "Career"
					link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
					target = "_blank"
		

	# About section
	[params.advantage]
		headline    = "Why Nebula"
		description = "blablablabla..."
		buttonText  = "Get started!"


	# Service section
	[params.features]
		headline = "Nebula Graph Features"

			[[params.features.list]]
				pic = "feature1.png"
				title = "Open Source"
				description = "We are looking forward to collaborating with the community to popularize and promote the graph database."

      [[params.features.list]]
				pic = "feature2.png"
				title = "High Performance"
				description = "Nebula Graph provides low latency read and write, while still maintaining high throughput."

			[[params.features.list]]
				pic = "feature3.png"
				title = "SQL-like"
				description = "Nebula Graph's SQL-like query language is easy to understand and powerful enough to meet complex business needs."

      [[params.features.list]]
				pic = "feature4.png"
				title = "Secure"
				description = "With role-based access control, Nebula Graph only allows authenticated access."

      [[params.features.list]]
				pic = "feature5.png"
				title = "Scalable"
				description = "With shared-nothing distributed architecture, Nebula Graph offers linear scalability."

      [[params.features.list]]
				pic = "feature6.png"
				title = "Extensible"
				description = "Nebula Graph supports multiple storage engine types. The query language can be extended to support new algorithms."

      [[params.features.list]]
				pic = "feature7.png"
				title = "Transactional"
				description = "With role-based access control, Nebula Graph only allows authenticated access."

      [[params.features.list]]
				pic = "feature8.png"
				title = "Highly Available"
				description = "Nebula Graph guarantees high availability even in case of failures."

	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
